# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    product_repository:
        class: AppBundle\Repository\ProductRepository
        autowire: true
        arguments:
            - '@api_client'
            - '@logger'

    api_client:
        class: GuzzleHttp\Client
        arguments:
            -
                base_uri: http://ec2-54-219-7-89.us-west-1.compute.amazonaws.com
