# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    product_repository_class: AppBundle\Repository\ProductRepository

services:
    product_repository:
        class: %product_repository_class%
        autowire: true
        arguments:
            - '@api_client'
            - '@logger'

    api_client:
        class: GuzzleHttp\Client
        arguments:
            -
                base_uri: http://ec2-54-219-7-89.us-west-1.compute.amazonaws.com

    query_string_authenticator:
        class: AppBundle\Security\QueryStringAuthenticator
        autowire: true

    our_user_provider:
        class: AppBundle\Security\OurUserProvider

    random_voter:
        class: AppBundle\Security\RandomVoter
        autowire: true
        tags:
            - { name: security.voter }
