services:
    api.client.api_client:
        class: GuzzleHttp\Client
        arguments:
            -
                base_uri: %api.host%
        public: false

    api.repository.product_repository:
        class: AppBundle\Repository\ProductRepository
        arguments:
            - '@api.client.api_client'
            - '@logger'
            - '@serializer'
